<template lang="pug">
div(class=`
    w-[100%]
    flex 
    flex-col 
    justify-center 
    items-end
    md:hidden
`)
    NuxtImg(
        @click='$emit("menuToogled")' 
        src='/img/headbutton.png' 
        alt='hamburger' 
        class=`
        w-[2rem] 
        h-[2rem] 
        mr-6
    `)
</template>
