<template lang="pug">
section(class=`
  bg-white
  w-screen
  pt-20
  flex
  justify-center
  mb-20
`)
  div(class=`
    w-[30%]
  `)
    div(class=`
      flex
      justify-left
      rotate-6
    `)
      NuxtImg(format='webp' 
        loading='lazy' 
        src='/img/php.svg' 
        alt='' 
        class=`
          w-[5rem] 
          md:w-[8rem]
        `)
    div(class=`
      rotate-[-17deg] 
      flex
      justify-center
    `)
      NuxtImg(
        format='webp' 
        loading='lazy' 
        src='/img/java.svg' 
        alt='' 
        class=`
          w-[5rem]
          md:w-[8rem]
        `)
    div(class=`
      flex
      justify-left
      rotate-6
    `)
      NuxtImg(
        format='webp' 
        loading='lazy' 
        src='/img/phyton.svg' 
        alt='' 
        class=`
          w-[5rem] 
          md:w-[8rem]
      `)
  div(class=`
    w-[30%]
  `)
    h3(class=`
        md:text-4xl 
        text-center
        my-6
        text-3xl
        font-semi-bold
    `) {{ $t(&quot;still_not_convinced&quot;) }}
    h3(class=`
      text-center
    `) {{ $t(&quot;maybe_our&quot;) }} 
      span(class=`
        text-sky-500 
      `) {{ $t(&quot;tech_stack&quot;) }}
      |  {{ $t(&quot;will_help&quot;) }}
  div(class=`
    w-[30%] 
    pl-[10%]
  `)
    div(class=`
      flex
      justify-left
      rotate-6
    `)
      NuxtImg(
        format='webp' 
        loading='lazy' 
        src='/img/laravel.svg' 
        alt='' 
        class=`
          w-[5rem] 
          md:w-[8rem]
        `)
    div(class=`
      rotate-[-17deg] 
      flex
      justify-center
    `)
      NuxtImg(
        format='webp' 
        loading='lazy' 
        src='/img/vue.svg' 
        alt='' 
        class=`
          w-[5rem] 
          md:w-[8rem]
        `)
    div(class=`
      flex
      justify-left
      rotate-6
    `)
      NuxtImg(
        format='webp' 
        loading='lazy' 
        src='/img/flutter.svg' 
        alt='' 
        class=`
          w-[5rem] 
          md:w-[8rem]
        `)
</template>