<template lang="pug">
section(class=`
  bg-white
  w-screen
  pt-20
  flex
  justify-center
  mb-20
  max-w-screen-xl
`)
  div(class=`
    w-[30%]
    ml-auto
    pl-[5%]
  `)
    div(class=`
      flex
      justify-left
      rotate-6
    `)
      NuxtImg(format='webp'
        loading='lazy'
        src='/img/php.svg'
        alt=''
        class=`
          w-[5rem]
          md:w-[8rem]
        `)
    div(class=`
      rotate-[-17deg]
      flex
      justify-center
    `)
      NuxtImg(
        format='webp'
        loading='lazy'
        src='/img/java.svg'
        alt=''
        class=`
          w-[5rem]
          md:w-[8rem]
        `)
    div(class=`
      flex
      justify-left
      rotate-6
    `)
      NuxtImg(
        format='webp'
        loading='lazy'
        src='/img/phyton.svg'
        alt=''
        class=`
          w-[5rem]
          md:w-[8rem]
      `)
  div(class=`
    w-[30%]
    m-auto
  `)
    h3(class=`
        md:text-4xl
        text-center
        my-6
        text-3xl
        font-semibold
    `) {{ $t('still_not_convinced') }}
    h3(class=`
      text-center
      text-xl
    `) {{ $t('maybe_our') }}
      span(class=`
        text-sky-500
      `) {{ $t('tech_stack') }}
      |  {{ $t('will_help') }}
  div(class=`
    w-[30%]
    pl-[10%]
  `)
    div(class=`
      flex
      justify-left
      rotate-6
    `)
      NuxtImg(
        format='webp'
        loading='lazy'
        src='/img/laravel.svg'
        alt=''
        class=`
          w-[5rem]
          md:w-[8rem]
        `)
    div(class=`
      rotate-[-17deg]
      flex
      justify-center
    `)
      NuxtImg(
        format='webp'
        loading='lazy'
        src='/img/vue.svg'
        alt=''
        class=`
          w-[5rem]
          md:w-[8rem]
        `)
    div(class=`
      flex
      justify-left
      rotate-6
    `)
      NuxtImg(
        format='webp'
        loading='lazy'
        src='/img/flutter.svg'
        alt=''
        class=`
          w-[5rem]
          md:w-[8rem]
        `)
</template>
