<template lang="pug">
section(class=`
  sm:px-[5%]
  md:text-left
  w-screen
  bg-white
  relative
  pt-40
  overflow-hidden
  text-center
  bg-[url('@/assets/img/top_friendshore_bg.webp')]
  bg-cover
  bg-no-repeat
  bg-center
  max-w-screen-xl
  sm:pb-[15%]
`)
  div(class=`
    justify-center
    relative
    m-auto
    md:flex 
    w-[90%]
  `)
    div
      h3(class=`
        lg:leading-normal
        relative
        text-5xl
        lg:text-6xl
        leading-relaxed
        z-10
      `) {{ $t('we_go_beyond') }}
        span(class=`
          text-sky-500
          font-bold
        `)  {{ $t('borders') }}
      h1(class=`
        relative
        my-6
        text-3xl
        z-10
      `) {{ $t('get_the_best') }}
    div(class=`
      flex
      justify-center
    `)
      img(
        src='@/assets/img/rocket.webp'
        alt='home background'
        class=`
        w-[90%]
        md:w-[30vw]
        relative
        z-30
      `)
  div(class=`
    sm:visible
    w-[200%]
    h-[200%]
    top-[40%]
    left-[-50%]
    bg-white
    absolute
    overflow-x-hidden
    rounded-t-[100%]
    z-20
  `)
  div(class=`
    w-[100%]
    mt-[10%]
    relative
    z-30
    pt-[15%]
  `)
    h1(class=`
      text-center
      md:my-20
      font-black
      text-2xl
    `) {{ $t('web_and_mobile') }}
    div(class=`
      md:flex
      justify-center
      mt-6
      hidden
    `)
      img(
        src='@/assets/img/our_services.webp'
        alt='our_services'
      )
    div(class=`
      md:hidden
      flex
      justify-center
      mt-6
    `)
      img(
        src='@/assets/img/mobile_our_services.webp'
        alt='our_services'
      )</template>
