<template lang="pug">
section(class=`
  sm:px-[5%] 
  md:text-left 
  w-screen
  min-h-screen
  bg-white
  relative
  pt-40
  overflow-hidden
  text-center
`)
  div(class=`
    w-[25rem]
    h-[25rem] 
    left-[12%] 
    top-[15%] 
    blur-[11rem] 
    rounded-full
    bg-violet-300
    absolute
    z-0
  `)
  div(class=`
    w-[25rem]
    h-[25rem]
    left-[40%]
    top-[25%]
    blur-[11rem] 
    rounded-full
    bg-blue-300
    absolute
    z-0
  `)
  div(class=`
    w-[25rem]
    h-[25rem]
    left-[70%]
    top-[15%]
    blur-[11rem] 
    rounded-full
    bg-violet-300
    absolute
    z-0
  `)
  div(class=`
    justify-center
    relative
    m-auto
    md:flex w-[90%] 
  `)
    div
      h3(class=`
        lg:leading-loose 
        relative
        text-6xl
        overflow-y-hidden
        leading-relaxed
        z-10
      `) {{ $t(&quot;we_go_beyond&quot;) }}
        span(class=`
          text-sky-500
          font-bold
        `)  {{ $t(&quot;borders&quot;) }}
      h1(class=`
        relative
        my-6
        text-3xl
        overflow-y-hidden
        z-10
      `) {{ $t(&quot;get_the_best&quot;) }}
    div(class=`
      flex
      justify-center
    `)
      NuxtImg(
        format='web' 
        loading='lazy' 
        src='/img/rocket.svg' 
        alt='home background' 
        class=`
        w-[90%]
        md:w-[28vw] 
        relative
        z-10
      `)
    div(class=`
      sm:visible 
      w-[200%]
      h-[200%]
      bottom-[-20%]
      left-[-20px]
      md:left-auto
      bg-white
      absolute
      overflow-x-hidden
      rounded-t-[100%]
    `)
  div(class=`
    w-[100%] 
    mt-[10%] 
    overflow-y-hidden
    relative
  `)
    h1(class=`
      text-center
      md:my-20
      font-black
      text-2xl
    `) {{ $t(&quot;web_and_mobile&quot;) }}
    div(class=`
      md:flex 
      justify-center
      mt-6
      hidden
    `)
      NuxtImg(
        format='webp' 
        loading='lazy' 
        src='/img/our_services.svg' 
        alt='our_services'
      )
    div(class=`
      md:hidden 
      flex
      justify-center
      mt-6
    `)
      NuxtImg(
        format='webp' 
        loading='lazy' 
        src='/img/mobile_our_services.svg' 
        alt='our_services'
      )

</template>
