<template lang="pug">
section(class=`
    w-screen
    justify-center
    bg-white
    relative
    py-24
    px-6
    overflow-hidden
    md:flex 
    md:px-0 
`)
    div(class=`
        w-[25rem] 
        h-[25rem] 
        left-[12%] 
        top-[15%] 
        blur-[11rem] 
        rounded-full
        bg-violet-300
        absolute
        z-0
    `)
    div(class=`
        w-[25rem] 
        h-[25rem] 
        left-[40%]
        top-[25%]
        blur-[11rem] 
        rounded-full.bg-blue-300.absolute.z-0
    `)
    div(class=`
        w-[25rem] 
        h-[25rem]
        left-[70%]
        top-[15%]
        blur-[11rem] 
        rounded-full
        bg-violet-300
        absolute
        z-0
    `)
    div(class=`
        md:mt-[15%] 
        lg:mt-[8%]
    `)
        h3(class=`
            md:text-4xl
            lg:text-5xl 
            text-5xl
            my-6
            overflow-y-hidden
            relative
        `) {{ $t('meet_the_team') }}
        h1(class=`
            md:text-4xl
            lg:text-5xl 
            text-sky-500
            my-6
            text-5xl
            font-bold
            overflow-y-hidden
            relative
        `) {{ $t('problem_solvers') }}
    div(class=`
        relative
    `)
        nuxt-img(
            format='webp' 
            loading='lazy' 
            src='/img/us_lines.svg' 
            alt='home background' 
            class=`
                w-[90%] 
                md:w-[45vw] 
                relative
                z-10
            `)
    div(class=`
        sm:visible 
        w-[200%] 
        h-[200%]
        top-[80%]
        left-[-50%]
        bg-white
        absolute
        overflow-x-hidden
        rounded-t-[100%]
    `)

</template>
