<template lang="pug">
section(class=`
    sm:px-[5%]
    md:text-left
    w-screen
    bg-purple-50
    relative
    pt-40
    overflow-hidden
    bg-[url('@/assets/img/top_team_bg.webp')]
    bg-cover
    bg-no-repeat
    bg-center
`)
    div(class=`
        justify-center
        relative
        m-auto
        md:flex w-[90%]
    `)
        div
            h3(class=`
            text-4xl
            lg:text-5xl
            md:mt-[30%]
            relative
            text-center
            md:text-start
            z-10
            `) {{ $t('meet_the_team') }}
            h1(class=`
            text-4xl
            lg:text-5xl
            text-sky-500
            mt-2
            mb-6
            font-bold
            relative
            text-center
            md:text-start
            `) {{ $t('problem_solvers') }}
        div(class=`
            relative
            z-10
            flex
            justify-center
        `)
            img(
            src='@/assets/img/us_lines.webp'
            alt='home background'
            class=`
                w-[90%]
                md:w-[50vw]
                relative
                z-30
                pb-44
                md:pb-22
                md:pl-[10%#f9fafb]
            `)
</template>
