<template lang="pug">
section(class=`
    w-screen
    bg-white
    z-40
    max-w-screen-xl
`)
    h3(class=`
        text-4xl
        font-bold
        text-center
        hidden
        md:block
    `) {{ $t('our_team') }}
    div(class=`
        flex
        justify-center
    `)
        NuxtImg(
            format='webp'
            loading='lazy'
            src='/img/mobile_team.svg'
            alt='team'
            class=`
                w-[90%]
                sm:w-[60%]
                my-6
                md:hidden
            `)
        NuxtImg(
        format='webp'
        loading='lazy'
        src='/img/team.svg'
        alt='home background'
        class=`
            hidden
            w-[90%]
            mx-[5%]
            mt-[10vh]
            md:w-[60vw]
            md:mx-[20vw]
            md:inline
        `)
</template>
