<template lang="pug">
section(class=`
  bg-white
  w-screen
  relative
  pb-[3rem]
  sm:pb-1
  max-w-screen-xl
`)
  div(class=`
    h-[50%]
    w-screen
    relative
    justify-center
    sm:flex
    px-[10%]
    sm:px-[5%]
    md:px-[10%]
    py-16
    lg:py-24
    bg-[url('@/assets/img/frienshore_home_background.webp')]
    bg-cover
    bg-no-repeat
    max-w-screen-xl
  `)
    div(class=`
      sm:mr-[10%]
      z-10
      relative
    `)
      h2(class=`
        leading-[3rem]
        lg:my-6
        text-3xl
        leading-normal
        lg:text-4xl
        text-center
        sm:text-start
      `)
        | {{ $t('we_go_beyond') }}
        strong {{ $t('borders') }}
      h2(class=`
        text-lg
        lg:text-2xl
        lg:my-6
        text-center
        sm:text-start
      `) {{ $t('discover_why') }}
      div(class=`
      flex
      justify-center
      sm:justify-start`)
        NuxtLink(to='/friendshore' class=`
        inline-block
        lg:text-lg
        my-6
        bg-black
        text-white
        rounded-full
        p-3
        px-7
        font-semibold
        text-lg      `) {{ $t('visit_friendshore') }}
    div(class=`
      flex
      justify-center
      sm:block`)
      img(
        src='@/assets/img/rocket.webp'
        alt='rocket'
        class=`
          max-w-[20rem]
          w-[90%]
          mt-[1%]
          z-10
          relative
          sm:w-[100%]
      `)
  div(class=`
    w-[90%]
    mx-auto
    lg:py-24
    my-20
  `)
    h1(class=`
      lg:text-3xl
      text-2xl
      text-center
      my-1
      font-semibold
    `)
      | {{ $t('the_key_to') }}
      br
      span(class=`
        text-sky-500
      `) {{ $t('strategy') }}
      |  {{ $t('behind') }}
    h2(class=`
      text-lg
      lg:text-xl
      text-center
      my-6
    `)
      | {{ $t('more_than') }}
      strong {{ $t('development_and_strategic') }}
      br
      |  {{ $t('with_necessary_expertise') }}
    ContactButton
    img(
      src="@/assets/img/line1_mobile.webp" 
      alt='arrow' 
      class=`
      absolute
      left-[10%]
      bottom-[-10rem]
      sm:hidden
      z-30
      min-[480px]:left-20
      min-[560px]:left-28
    `)
    img(
      src="@/assets/img/line1.webp" 
      alt='arrow' 
      class=`
      z-30
      hidden 
      w-[18rem] 
      absolute
      sm:bottom-[-7rem]
      lg:bottom-[-2rem]
      right-[49.5%]
      sm:inline 
      xl:w-[30rem]
      xl:bottom-[-8rem]`)
</template>
