<template lang="pug">
section(class=`
  md:flex 
  w-screen
  bg-white
  justify-center
  my-20
  relative
`)
  img(
    src="@/assets/img/line4_mobile.webp" 
    alt='arrow' 
    class=`
      absolute 
      right-[75%] 
      top-[10rem] 
      z-30
      md:hidden
  `)
  img(
    src="@/assets/img/line4.webp" 
    alt='arrow' 
    class=`
      hidden
      absolute 
      w-[8rem]
      right-[40%]
      top-[10rem]
      z-30
      md:inline
      lg:w-[10rem]
      xl:w-[8rem]
      xl:right-[43%]
      xl:top-[12rem]
      2xl:right-[46%]
      2xl:top-[17rem]
  `)  
  div(class=`
      md:mt-[12vh]
      xl:mt-[18vh]
      2xl:mt-[22vh]
      md:pr-2
      lg:pr-16
  `)
    h3(class=`
      md:text-start 
      text-3xl
      font-semibold
      my-6
      text-center
    `) {{ $t('you_can_find') }} 
      NuxtLink(
        to="https://goo.gl/maps/SqqtACYBkVQMjRv39"
        class=`
        hover:underline
        text-sky-500  
      `) {{ $t('here') }}
    h3(class=`
      md:text-start 
      my-6
      text-lg
      text-center
    `) {{ $t('tell_us_your') }}
      br
      |  {{ $t('or_fill_out') }} 
      br
      |  {{ $t('we_will_contact') }}
    ContactButton
  div(class=`
    flex
    justify-center
  `)
    img(
      src='@/assets/img/building.webp' 
      alt='building' 
      class=`
      w-[75%] 
      my-[5%]
      md:my-0
      md:w-[20rem]
      md:ml-[5rem]
      pl-6
    `)
</template>
