<template lang="pug">
section(class=`
  bg-white
  w-screen
  relative
  overflow-hidden
`)
  div(class=`
    h-[50%] 
    px-[5%] 
    w-screen
    relative
    overflow-hidden
    py-6
    justify-center
    sm:flex 
    lg:px-[10%] 
    lg:py-24 
  `)
    div(class=`
      w-[25rem] 
      h-[25rem] 
      left-[6%] 
      top-[15%] 
      blur-[11rem] 
      rounded-full
      bg-violet-300
      absolute
      z-0
    `)
    div(class=`
      w-[25rem] 
      h-[25rem] 
      left-[40%] 
      top-[-10%] 
      blur-[11rem] 
      rounded-full
      bg-blue-300
      absolute
      z-0
    `)
    div(class=`
      w-[25rem] 
      h-[25rem] 
      left-[75%] 
      top-[15%] 
      blur-[11rem] 
      rounded-full
      bg-violet-300
      absolute
      z-0
    `)
    div(class=`
      mr-[10%] 
      z-10
      overflow-y-hidden
      relative
    `)
      h2(class=`
        leading-[3rem] 
        lg:my-6 
        text-2xl
        leading-normal
        overflow-y-hidden
        lg:text-4xl 
      `)
        | {{ $t('we_go_beyond') }} 
        strong {{ $t('borders') }}
      h2(class=`
        text-xs
        overflow-y-hidden
        lg:text-2xl 
        lg:my-6 
      `) {{ $t('discover_why') }}
      NuxtLink(to='/friendshore' class=`
        inline-block
        lg:text-lg 
        my-6
        bg-black
        text-white
        rounded-full
        p-3
        px-7
        font-semibold
        text-sm
      `) {{ $t('visit_friendshore') }}
    NuxtImg(
      format="webp"
      loading="lazy"
      src='/img/rocket.png' 
      alt='rocket' 
      class=`
        w-[90%] 
        mt-[1%] 
        z-10
        relative
        sm:w-[50%] 
    `)
  div(class=`
    w-[90%] 
    mx-auto
    lg:py-24 
    my-20
  `)
    h1(class=`
      lg:text-3xl 
      text-2xl
      text-center
      my-1
      font-semibold
      overflow-y-hidden
    `)
      | {{ $t('the_key_to') }} 
      br
      span(class=`
        text-sky-500
      `) {{ $t('strategy') }}
      |  {{ $t('behind') }}
    h2(class=`
      text-lge
      text-center
      my-6
    `)
      | {{ $t('more_than') }} 
      strong {{ $t('development_and_strategic') }}
      br
      |  {{ $t('with_necessary_expertise') }}
    ContactButton
</template>