<template lang="pug">
section(class=`
  md:flex 
  w-screen
  bg-white
  justify-center
  my-20
  relative
`)
  NuxtImg(
    src="/img/line4_mobile.svg" 
    alt='arrow' 
    class=`
      absolute 
      right-[75%] 
      top-[10rem] 
      z-30
      md:hidden
  `)
  NuxtImg(
    src="/img/line4.svg" 
    alt='arrow' 
    class=`
      hidden
      absolute
      right-[75%] 
      top-[10rem] 
      z-30
      md:inline
  `)  
  div(class=`
    md:mt-[25vh]
  `)
    h3(class=`
      md:text-start 
      text-3xl
      font-semibold
      overflow-y-hidden
      my-6
      text-center
    `) {{ $t('you_can_find') }} 
      NuxtLink(
        to="https://goo.gl/maps/SqqtACYBkVQMjRv39"
        class=`
        hover:underline
        text-sky-500  
      `) {{ $t('here') }}
    h3(class=`
      md:text-start 
      my-6
      text-center
      text-center
    `) {{ $t('tell_us_your') }}
      br
      |  {{ $t('or_fill_out') }} 
      br
      |  {{ $t('we_will_contact') }}
    ContactButton
  div(class=`
    flex
    justify-center
  `)
    NuxtImg(
      format="web"
      loading="lazy"
      src='/img/building.png' 
      alt='building' 
      class=`
      w-[75%] 
      my-[5%]
      md:my-0
      md:w-[17vw]
      md:h-[30vw] 
      pl-6
    `)
</template>
