<template lang="pug">
section(class=`
  w-[100vw]
  bg-white
  min-h-screen
  absolute
  left-0
  overflow-x-hidden
  overflow-y-hidden
  md:w-[100vw]
  md:h-[20vw]
  md:min-h-[20vw]
  md:right-[-10%]
  md:rounded-tl-[100%]
  md:rounded-tr-[100%] 
`)
  div(class=`
    w-[25rem]
    h-[25rem]
    left-[6%]
    top-[15%]
    blur-[11rem] 
    rounded-full
    bg-violet-300
    absolute
  `)
  div(class=`
    w-[25rem]
    h-[25rem]
    left-[40%]
    top-[-10%]
    blur-[11rem]
    rounded-full
    bg-blue-300
    absolute
  `)
  div(class=`
    w-[25rem]
    h-[25rem]
    left-[75%]
    top-[15%]
    blur-[11rem] 
    rounded-full
    bg-violet-300
    absolute
  `)
  div(class=`
    md:h-[60%]
    sm:mt-[4%]
    md:flex
    md:justify-center
    mt-[20%] 
    block
    w-screen
    relative
  `)
    div(class=`
      px-[10%]
      md:px-[0]
      md:py-6 
      py-12
      flex
      justify-center
    `)
      NuxtImg(
        loading="lazy"
        src='/img/logo.svg' 
        alt='logo controlla' 
        class=`
        w-[80%]
        md:w-[100%]
        max-w-[20rem]
      `)
    div(class=`
      mx-[5%]
    `)
      h3(class=`
        md:text-left 
        text-2xl
        my-6
        text-center
      `) {{ $t('lets_work') }} 
        strong {{ $t('together') }}
      ContactButton
    div(class=`
      mx-[5%]
      my-6
    `)
      h3(class=`
        text-xl
        leading-8
        text-center
        md:text-left 
      `) {{ $t('services') }} 
        br
        |  {{ $t('success') }} 
        br
        |  {{ $t('portfolio') }}
    .my-6(class=`
      mx-[5%]
    `)
      h3(class=`
        md:text-left 
        text-xl
        leading-8
        text-center
      `) {{ $t('Us') }} 
        br
        |  {{ $t('terms') }} 
        br
        |  {{ $t('privacy') }}
  div(class=`
    h-[25%] 
    w-screen
    relative
  `)
    div(class=`
      flex
      justify-center
      mb-6
    `)
      NuxtLink(to='https://www.facebook.com/')
        NuxtImg(
          loading="lazy"
          src='/img/facebook.svg' 
          alt='logo facebook' 
          class=`
          mx-6
        `)
      NuxtLink(to='https://www.instagram.com/controlla_technologies/')
        NuxtImg(
          loading="lazy"
          src='/img/instagram.svg' 
          alt='logo instagram' 
          class=`
          mx-6
        `)
      NuxtLink(to='https://www.linkedin.com/company/controlla/')
        NuxtImg(
          src='/img/linkedin.svg' 
          alt='logo linkedin' 
          class=`
          mx-6
        `)
    h3(class=`
      text-center
      text-xs
    `) {{ $t('copyright') }}
</template>